version: '3.3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_mytask
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DATABASE: db_mytask
      POSTGRES_USER: user_mytask
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'